version: '3.8'

services:
  redis:
    container_name: redis_nex
    image: redis
    ports:
      - "6380:6379"

  postgres:
    image: postgres:latest
    container_name: postgres_nex
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
